[lsm]
[lsm.core]
LSM_TOL_MEM_SIZE_LIMIT = 67108864
LSM_PER_MEM_SIZE_LIMIT = 4194304
LSM_SST_LEVEL_RATIO = 4
LSM_BLOCK_SIZE = 32768

[lsm.cache]
LSM_BLOCK_CACHE_CAPACITY = 1024
LSM_BLOCK_CACHE_K = 8

[redis]
REDIS_EXPIRE_HEADER = "REDIS_EXPIRE_"
REDIS_HASH_VALUE_PREFFIX = "REDIS_HASH_VALUE_"
REDIS_FIELD_PREFIX = "REDIS_FIELD_"
REDIS_FIELD_SEPARATOR = "$"
REDIS_LIST_SEPARATOR = "#"
REDIS_SORTED_SET_PREFIX = "REDIS_SORTED_SET_"
REDIS_SET_PREFIX = "REDIS_SET_"
REDIS_SORTED_SET_SCORE_LEN = 32

[bloom_filter]
BLOOM_FILTER_EXPECTED_SIZE = 65536
BLOOM_FILTER_EXPECTED_ERROR_RATE = 0.1

